---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 500d064f9fba216c952cce79046d26fcc7747e04
    app.quarkus.io/build-timestamp: 2023-04-05 - 15:43:21 +0000
  labels:
    app.kubernetes.io/name: person-service
    app.kubernetes.io/version: 1.6.0
  name: person-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: person-service
    app.kubernetes.io/version: 1.6.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 500d064f9fba216c952cce79046d26fcc7747e04
    app.quarkus.io/build-timestamp: 2023-04-05 - 15:43:21 +0000
  labels:
    app.kubernetes.io/name: person-service
    app.kubernetes.io/version: 1.6.0
  name: person-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: person-service
      app.kubernetes.io/version: 1.6.0
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 500d064f9fba216c952cce79046d26fcc7747e04
        app.quarkus.io/build-timestamp: 2023-04-05 - 15:43:21 +0000
      labels:
        app.kubernetes.io/name: person-service
        app.kubernetes.io/version: 1.6.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/wpernath/person-service:latest
          imagePullPolicy: Always
          name: person-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
